### ISSUE TITLE
getting an error from /src/lib/env.js:10 since 6.0.0

### ISSUE THREAD

**Issue by ValentinOdier** [FGRibreau/common-env#22]
Hi,

node : 4.5.0
npm: 3.9.0
common-env: 6.0.0

I'm getting : 

```
/usr/src/app/node_modules/common-env/src/lib/env.js:10
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/src/app/node_modules/common-env/src/lib/index.js:2:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

i had no problem with 5.x versions.

Maybe it has to do with my nodeJs version

Tell me if you need/want more info.

Merci :)

**Comment by FGRibreau** [comment]
Hello @ValentinOdier,

Common-env v6 dropped support for Node 4-5, and only supports v6+, that's why :)
